/*
LOOKUPITEMCODE
OLE DB DESTINATION
EMAILNOTIFICATION
DEPOSITVALUELOG
NORMAORDERS
STORE_CONNECTION
AREACONFIGURATIONS
VWBTECHSMCHECKSTOREOMS
DELIVERYCHARGESCONFIGURATIONS
USERWAREHOUSES
ORDER
RMSWAREHOUSEDICOUNTS
DATALOGS
WORKFLOWSTAGES
STOR
GET_CBM_CAPACITY_DATA
DISTRIBUTIONCENTER21102019
INSTALLMENTORDERS
WORKFLOWSTATUSES
REGIONS
AREADETAILSCONFIGURATION
CBMCAPACITY
ORDERDIMENSIONS
SYSDIAGRAMS
TRANSFERORDERTEMP
LOYALTYSERVICEHEADER
*/

SELECT 
'select '''||TABLE_NAME||''' as Table_name,count(*) from LANDING_OMS.'||TABLE_NAME||' UNION ' 
FROM CFG.OMS_LOADING_TABLE_NAME;




--'SELECT '''||TABLE_NAME||''' AS TABLE_NAME,COUNT(*) FROM LANDING_OMS."'||TABLE_NAME||'" UNION '

select 'REGIONS21102019' as Table_name,count(*) from LANDING_OMS.REGIONS21102019 UNION 
select 'TAXEXEMPTION' as Table_name,count(*) from LANDING_OMS.TAXEXEMPTION UNION 
select 'DISTRICTS21102019' as Table_name,count(*) from LANDING_OMS.DISTRICTS21102019 UNION 
select 'DISTRIBUTIONCENTER21102019' as Table_name,count(*) from LANDING_OMS.DISTRIBUTIONCENTER21102019 UNION 
select 'TEMP_DISTRICT' as Table_name,count(*) from LANDING_OMS.TEMP_DISTRICT UNION 
select 'LOOKUPITEMCODE' as Table_name,count(*) from LANDING_OMS.LOOKUPITEMCODE UNION 
select 'DIST' as Table_name,count(*) from LANDING_OMS.DIST UNION 
select 'REG' as Table_name,count(*) from LANDING_OMS.REG UNION 
select 'REASONS' as Table_name,count(*) from LANDING_OMS.REASONS UNION 
select 'EXCEPTIONLOG' as Table_name,count(*) from LANDING_OMS.EXCEPTIONLOG UNION 
select 'WFSTEPS' as Table_name,count(*) from LANDING_OMS.WFSTEPS UNION 
select 'SYNCHONLINELOGS' as Table_name,count(*) from LANDING_OMS.SYNCHONLINELOGS UNION 
select 'OMSAREA' as Table_name,count(*) from LANDING_OMS.OMSAREA UNION 
select 'SUBREGIONSTORES' as Table_name,count(*) from LANDING_OMS.SUBREGIONSTORES UNION 
select 'STOREAREA' as Table_name,count(*) from LANDING_OMS.STOREAREA UNION 
select 'TMPDISTRICT' as Table_name,count(*) from LANDING_OMS.TMPDISTRICT UNION 
select 'SALESCHANNELS' as Table_name,count(*) from LANDING_OMS.SALESCHANNELS UNION 
select 'DISTRICTS' as Table_name,count(*) from LANDING_OMS.DISTRICTS UNION 
select 'BUNDLEITEMSLOG' as Table_name,count(*) from LANDING_OMS.BUNDLEITEMSLOG UNION 
select 'STOREMOBILITYUSERSCATEGORY' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERSCATEGORY UNION 
select 'STOREMOBILITYUSERSBRAND' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERSBRAND UNION 
select 'STOREMOBILITYUSERROLES' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERROLES UNION 
select 'ASPNETUSERCLAIMS' as Table_name,count(*) from LANDING_OMS.ASPNETUSERCLAIMS UNION 
select 'ASPNETUSERLOGINS' as Table_name,count(*) from LANDING_OMS.ASPNETUSERLOGINS UNION 
select 'AREACONFIGURATIONS_2022' as Table_name,count(*) from LANDING_OMS.AREACONFIGURATIONS_2022 UNION 
--select 'OLE DB DESTINATION' as Table_name,count(*) from LANDING_OMS.OLE DB DESTINATION UNION 
select 'CONFIGUR' as Table_name,count(*) from LANDING_OMS.CONFIGUR UNION 
select 'REGIONRMSWAREHOUSE' as Table_name,count(*) from LANDING_OMS.REGIONRMSWAREHOUSE UNION 
select 'NEW_SHENCHTB' as Table_name,count(*) from LANDING_OMS.NEW_SHENCHTB UNION 
select 'DOWNPAYMENTSLA' as Table_name,count(*) from LANDING_OMS.DOWNPAYMENTSLA UNION 
select 'TOURS' as Table_name,count(*) from LANDING_OMS.TOURS UNION 
select 'QUOTATION' as Table_name,count(*) from LANDING_OMS.QUOTATION UNION 
select 'ASPNETROLES' as Table_name,count(*) from LANDING_OMS.ASPNETROLES UNION 
select 'USERWAREHOUSES' as Table_name,count(*) from LANDING_OMS.USERWAREHOUSES UNION 
select 'MENUS' as Table_name,count(*) from LANDING_OMS.MENUS UNION 
select 'RMSWAREHOUSE' as Table_name,count(*) from LANDING_OMS.RMSWAREHOUSE UNION 
select 'DEPOSITVALUELOG' as Table_name,count(*) from LANDING_OMS.DEPOSITVALUELOG UNION 
select 'REASONROLE' as Table_name,count(*) from LANDING_OMS.REASONROLE UNION 
select 'RMSWAREHOUSEDICOUNTS' as Table_name,count(*) from LANDING_OMS.RMSWAREHOUSEDICOUNTS UNION 
select 'STOREMOBILITYUSERSBACKUP' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERSBACKUP UNION 
select 'ORDERTYPES' as Table_name,count(*) from LANDING_OMS.ORDERTYPES UNION 
select 'CONFIGURATION' as Table_name,count(*) from LANDING_OMS.CONFIGURATION UNION 
select 'ASPNETUSERROLES' as Table_name,count(*) from LANDING_OMS.ASPNETUSERROLES UNION 
select 'ORDERENTRYBAK' as Table_name,count(*) from LANDING_OMS.ORDERENTRYBAK UNION 
select 'ORDERDIMENSIONS' as Table_name,count(*) from LANDING_OMS.ORDERDIMENSIONS UNION 
select 'EMAILNOTIFICATIONLOG' as Table_name,count(*) from LANDING_OMS.EMAILNOTIFICATIONLOG UNION 
select 'STORE_ORDERSSYNCLOG' as Table_name,count(*) from LANDING_OMS.STORE_ORDERSSYNCLOG UNION 
select 'DRAFTONLINEORDER_21112019' as Table_name,count(*) from LANDING_OMS.DRAFTONLINEORDER_21112019 UNION 
select 'STOCKTMP' as Table_name,count(*) from LANDING_OMS.STOCKTMP UNION 
select 'INSTALLMENTORDERS' as Table_name,count(*) from LANDING_OMS.INSTALLMENTORDERS UNION 
select 'SYSDIAGRAMS' as Table_name,count(*) from LANDING_OMS.SYSDIAGRAMS UNION 
select 'STORE_CONNECTION' as Table_name,count(*) from LANDING_OMS.STORE_CONNECTION UNION 
select 'INTERMEDIATEONLINEORDERS' as Table_name,count(*) from LANDING_OMS.INTERMEDIATEONLINEORDERS UNION 
select 'WORKFLOWSTAGES' as Table_name,count(*) from LANDING_OMS.WORKFLOWSTAGES UNION 
select 'MISSING_DATA_NPS_TEMP' as Table_name,count(*) from LANDING_OMS.MISSING_DATA_NPS_TEMP UNION 
select 'WFACTIONS' as Table_name,count(*) from LANDING_OMS.WFACTIONS UNION 
select 'WORKFLOWSTATUSES' as Table_name,count(*) from LANDING_OMS.WORKFLOWSTATUSES UNION 
select 'SUBREGIONS' as Table_name,count(*) from LANDING_OMS.SUBREGIONS UNION 
select 'USERCARS' as Table_name,count(*) from LANDING_OMS.USERCARS UNION 
select 'STOREMOBILITYUSERSVERSIONS' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERSVERSIONS UNION 
select 'AREALOOPINGSTORES' as Table_name,count(*) from LANDING_OMS.AREALOOPINGSTORES UNION 
select 'DATALOGS' as Table_name,count(*) from LANDING_OMS.DATALOGS UNION 
select 'AREALOOPINGSTORES_2022' as Table_name,count(*) from LANDING_OMS.AREALOOPINGSTORES_2022 UNION 
select 'RMSWAREHOUSEDICOUNTS_BK' as Table_name,count(*) from LANDING_OMS.RMSWAREHOUSEDICOUNTS_BK UNION 
select 'COURRIER' as Table_name,count(*) from LANDING_OMS.COURRIER UNION 
select 'NPS' as Table_name,count(*) from LANDING_OMS.NPS UNION 
select 'CARS' as Table_name,count(*) from LANDING_OMS.CARS UNION 
select 'SHEET' as Table_name,count(*) from LANDING_OMS.SHEET UNION 
select 'STORESCONNECTION' as Table_name,count(*) from LANDING_OMS.STORESCONNECTION UNION 
select 'MWLOG' as Table_name,count(*) from LANDING_OMS.MWLOG UNION 
select 'STOR' as Table_name,count(*) from LANDING_OMS.STOR UNION 
select 'ORDERENTERYBEFOREDELETE' as Table_name,count(*) from LANDING_OMS.ORDERENTERYBEFOREDELETE UNION 
select 'STOREMOBILITYUSERS' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERS UNION 
select 'AREACONFIGURATIONS' as Table_name,count(*) from LANDING_OMS.AREACONFIGURATIONS UNION 
select 'DISTRIBUTIONCENTER' as Table_name,count(*) from LANDING_OMS.DISTRIBUTIONCENTER UNION 
select 'ACTIONSLOGS' as Table_name,count(*) from LANDING_OMS.ACTIONSLOGS UNION 
select 'VERSIONCONFIGURATION' as Table_name,count(*) from LANDING_OMS.VERSIONCONFIGURATION UNION 
select '__MIGRATIONHISTORY' as Table_name,count(*) from LANDING_OMS.__MIGRATIONHISTORY UNION 
select 'ACTIONREASONS' as Table_name,count(*) from LANDING_OMS.ACTIONREASONS UNION 
select 'CUSTOMERCOORDINATES' as Table_name,count(*) from LANDING_OMS.CUSTOMERCOORDINATES UNION 
select 'ASPNETUSERS' as Table_name,count(*) from LANDING_OMS.ASPNETUSERS UNION 
select 'QUOTATIONENTRY' as Table_name,count(*) from LANDING_OMS.QUOTATIONENTRY UNION 
select 'TRANSFERORDERLOGS' as Table_name,count(*) from LANDING_OMS.TRANSFERORDERLOGS UNION 
select 'NORMAORDERS' as Table_name,count(*) from LANDING_OMS.NORMAORDERS UNION 
select 'WORKORDER' as Table_name,count(*) from LANDING_OMS.WORKORDER UNION 
select 'TOURSTATUSES' as Table_name,count(*) from LANDING_OMS.TOURSTATUSES UNION 
select 'GET_CBM_CAPACITY_DATA' as Table_name,count(*) from LANDING_OMS.GET_CBM_CAPACITY_DATA UNION 
select 'LOYALTYSERVICEATTRIBUTES' as Table_name,count(*) from LANDING_OMS.LOYALTYSERVICEATTRIBUTES UNION 
select 'SUBMENUS' as Table_name,count(*) from LANDING_OMS.SUBMENUS UNION 
select 'EMAILNOTIFICATION' as Table_name,count(*) from LANDING_OMS.EMAILNOTIFICATION UNION 
select 'LOOPINGSTORESCONFIGURATION' as Table_name,count(*) from LANDING_OMS.LOOPINGSTORESCONFIGURATION UNION 
select 'ORDERSSYNCLOG' as Table_name,count(*) from LANDING_OMS.ORDERSSYNCLOG UNION 
select 'ANNUALVACATIONS' as Table_name,count(*) from LANDING_OMS.ANNUALVACATIONS UNION 
--select 'ORDER' as Table_name,count(*) from LANDING_OMS.ORDER UNION 
select 'DRIVERS' as Table_name,count(*) from LANDING_OMS.DRIVERS UNION 
select 'ORDERVERSIONENTRY' as Table_name,count(*) from LANDING_OMS.ORDERVERSIONENTRY UNION 
select 'DELIVERYCHARGESCONFIGURATIONS' as Table_name,count(*) from LANDING_OMS.DELIVERYCHARGESCONFIGURATIONS UNION 
select 'SECONDARYDISTIBUTIONCENTER' as Table_name,count(*) from LANDING_OMS.SECONDARYDISTIBUTIONCENTER UNION 
select 'SETTINGVALUES' as Table_name,count(*) from LANDING_OMS.SETTINGVALUES UNION 
select 'OLD_DISTRICT' as Table_name,count(*) from LANDING_OMS.OLD_DISTRICT UNION 
select 'AREADETAILSCONFIGURATION_2022' as Table_name,count(*) from LANDING_OMS.AREADETAILSCONFIGURATION_2022 UNION 
select 'WORKFLOWS' as Table_name,count(*) from LANDING_OMS.WORKFLOWS UNION 
select 'LOYALTYPAYMENTDATALOG' as Table_name,count(*) from LANDING_OMS.LOYALTYPAYMENTDATALOG UNION 
select 'LOYALTYSERVICEHEADER' as Table_name,count(*) from LANDING_OMS.LOYALTYSERVICEHEADER UNION 
select 'INSPERIOD' as Table_name,count(*) from LANDING_OMS.INSPERIOD UNION 
select 'USERSTEMP' as Table_name,count(*) from LANDING_OMS.USERSTEMP UNION 
select 'ORDERVESIONS' as Table_name,count(*) from LANDING_OMS.ORDERVESIONS UNION 
select 'WFSTATUSES' as Table_name,count(*) from LANDING_OMS.WFSTATUSES UNION 
select 'REGIONS' as Table_name,count(*) from LANDING_OMS.REGIONS UNION 
select 'ROLEMENUS' as Table_name,count(*) from LANDING_OMS.ROLEMENUS UNION 
select 'WORKFLOWSTEPS' as Table_name,count(*) from LANDING_OMS.WORKFLOWSTEPS UNION 
select 'CANCELINSTORDERS' as Table_name,count(*) from LANDING_OMS.CANCELINSTORDERS UNION 
--select 'VWBTECHSMCHECKSTOREOMS' as Table_name,count(*) from LANDING_OMS.VWBTECHSMCHECKSTOREOMS UNION -- DOES NOT EXIST OR NOT AUTHORIZED
select 'LOG' as Table_name,count(*) from LANDING_OMS.LOG UNION 
select 'TRANSFERORDERTEMP' as Table_name,count(*) from LANDING_OMS.TRANSFERORDERTEMP UNION 
select 'NUMBERS' as Table_name,count(*) from LANDING_OMS.NUMBERS UNION 
select 'SETTINGS' as Table_name,count(*) from LANDING_OMS.SETTINGS UNION 
select 'DISTRICTS18102019' as Table_name,count(*) from LANDING_OMS.DISTRICTS18102019 UNION 
select 'AREADETAILSCONFIGURATION' as Table_name,count(*) from LANDING_OMS.AREADETAILSCONFIGURATION UNION 
select 'CBMCAPACITY' as Table_name,count(*) from LANDING_OMS.CBMCAPACITY UNION 
select 'STOREDLOGACTION' as Table_name,count(*) from LANDING_OMS.STOREDLOGACTION UNION 
select 'ONLINESYNCORDERVERSIONSLOG' as Table_name,count(*) from LANDING_OMS.ONLINESYNCORDERVERSIONSLOG UNION 
select 'ORDERENTRY' as Table_name,count(*) from LANDING_OMS.ORDERENTRY UNION 
select 'WORKFLOWACTIONS' as Table_name,count(*) from LANDING_OMS.WORKFLOWACTIONS;





SELECT 
'select '''||TABLE_NAME||''' as Table_name,count(*) from LANDING_OMS.'||TABLE_NAME||' UNION ' 
FROM information_schema.tables
where table_schema = 'LANDING_OMS';


select 'ACTIONSLOGS' as Table_name,count(*) from LANDING_OMS.ACTIONSLOGS UNION 
select 'AREACONFIGURATIONS' as Table_name,count(*) from LANDING_OMS.AREACONFIGURATIONS UNION 
select 'AREACONFIGURATIONS_2022' as Table_name,count(*) from LANDING_OMS.AREACONFIGURATIONS_2022 UNION 
select 'AREALOOPINGSTORES_2022' as Table_name,count(*) from LANDING_OMS.AREALOOPINGSTORES_2022 UNION 
select 'ASPNETUSERCLAIMS' as Table_name,count(*) from LANDING_OMS.ASPNETUSERCLAIMS UNION 
select 'DELIVERYCHARGESCONFIGURATIONS' as Table_name,count(*) from LANDING_OMS.DELIVERYCHARGESCONFIGURATIONS UNION 
select 'DEPOSITVALUELOG' as Table_name,count(*) from LANDING_OMS.DEPOSITVALUELOG UNION 
select 'INSPERIOD' as Table_name,count(*) from LANDING_OMS.INSPERIOD UNION 
select 'MWLOG' as Table_name,count(*) from LANDING_OMS.MWLOG UNION 
select 'AREADETAILSCONFIGURATION' as Table_name,count(*) from LANDING_OMS.AREADETAILSCONFIGURATION UNION 
select 'BUNDLEITEMSLOG' as Table_name,count(*) from LANDING_OMS.BUNDLEITEMSLOG UNION 
select 'DIST' as Table_name,count(*) from LANDING_OMS.DIST UNION 
select 'DRIVERS' as Table_name,count(*) from LANDING_OMS.DRIVERS UNION 
select 'LOYALTYPAYMENTDATALOG' as Table_name,count(*) from LANDING_OMS.LOYALTYPAYMENTDATALOG UNION 
select 'ORDERDIMENSIONS' as Table_name,count(*) from LANDING_OMS.ORDERDIMENSIONS UNION 
select 'REGIONRMSWAREHOUSE' as Table_name,count(*) from LANDING_OMS.REGIONRMSWAREHOUSE UNION 
select 'SETTINGS' as Table_name,count(*) from LANDING_OMS.SETTINGS UNION 
select 'STOREMOBILITYUSERSBACKUP' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERSBACKUP UNION 
select 'STOREMOBILITYUSERSCATEGORY' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERSCATEGORY UNION 
select 'TEMP_DISTRICT' as Table_name,count(*) from LANDING_OMS.TEMP_DISTRICT UNION 
select 'TRANSFERORDERLOGS' as Table_name,count(*) from LANDING_OMS.TRANSFERORDERLOGS UNION 
select 'USERWAREHOUSES' as Table_name,count(*) from LANDING_OMS.USERWAREHOUSES UNION 
select 'WFSTATUSES' as Table_name,count(*) from LANDING_OMS.WFSTATUSES UNION 
select 'WORKFLOWACTIONS' as Table_name,count(*) from LANDING_OMS.WORKFLOWACTIONS UNION 
select 'WORKFLOWSTAGES' as Table_name,count(*) from LANDING_OMS.WORKFLOWSTAGES UNION 
select 'WORKFLOWSTATUSES' as Table_name,count(*) from LANDING_OMS.WORKFLOWSTATUSES UNION 
select 'STOR' as Table_name,count(*) from LANDING_OMS.STOR UNION 
select 'TRANSFERORDERTEMP' as Table_name,count(*) from LANDING_OMS.TRANSFERORDERTEMP UNION 
select 'SYSDIAGRAMS' as Table_name,count(*) from LANDING_OMS.SYSDIAGRAMS UNION 
select 'USERCARS' as Table_name,count(*) from LANDING_OMS.USERCARS UNION 
select 'ORDERTYPES' as Table_name,count(*) from LANDING_OMS.ORDERTYPES UNION 
select 'ANNUALVACATIONS' as Table_name,count(*) from LANDING_OMS.ANNUALVACATIONS UNION 
select 'ASPNETROLES' as Table_name,count(*) from LANDING_OMS.ASPNETROLES UNION 
select 'COURRIER' as Table_name,count(*) from LANDING_OMS.COURRIER UNION 
select 'CUSTOMERCOORDINATES' as Table_name,count(*) from LANDING_OMS.CUSTOMERCOORDINATES UNION 
select 'DISTRICTS' as Table_name,count(*) from LANDING_OMS.DISTRICTS UNION 
select 'GET_CBM_CAPACITY_DATA' as Table_name,count(*) from LANDING_OMS.GET_CBM_CAPACITY_DATA UNION 
select 'LOYALTYSERVICEATTRIBUTES' as Table_name,count(*) from LANDING_OMS.LOYALTYSERVICEATTRIBUTES UNION 
select 'MENUS' as Table_name,count(*) from LANDING_OMS.MENUS UNION 
select 'NPS' as Table_name,count(*) from LANDING_OMS.NPS UNION 
select 'ONLINESYNCORDERVERSIONSLOG' as Table_name,count(*) from LANDING_OMS.ONLINESYNCORDERVERSIONSLOG UNION 
select 'ORDERENTERYBEFOREDELETE' as Table_name,count(*) from LANDING_OMS.ORDERENTERYBEFOREDELETE UNION 
select 'ROLEMENUS' as Table_name,count(*) from LANDING_OMS.ROLEMENUS UNION 
select 'WORKORDER' as Table_name,count(*) from LANDING_OMS.WORKORDER UNION 
select 'CANCELINSTORDERS' as Table_name,count(*) from LANDING_OMS.CANCELINSTORDERS UNION 
select 'DISTRICTS21102019' as Table_name,count(*) from LANDING_OMS.DISTRICTS21102019 UNION 
select 'ORDERENTRYBAK' as Table_name,count(*) from LANDING_OMS.ORDERENTRYBAK UNION 
select 'QUOTATION' as Table_name,count(*) from LANDING_OMS.QUOTATION UNION 
select 'RMSWAREHOUSEDICOUNTS' as Table_name,count(*) from LANDING_OMS.RMSWAREHOUSEDICOUNTS UNION 
select 'SETTINGVALUES' as Table_name,count(*) from LANDING_OMS.SETTINGVALUES UNION 
select 'STOREMOBILITYUSERS' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERS UNION 
select 'STOREMOBILITYUSERSVERSIONS' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERSVERSIONS UNION 
select 'STORE_ORDERSSYNCLOG' as Table_name,count(*) from LANDING_OMS.STORE_ORDERSSYNCLOG UNION 
select 'SUBMENUS' as Table_name,count(*) from LANDING_OMS.SUBMENUS UNION 
select 'TMPDISTRICT' as Table_name,count(*) from LANDING_OMS.TMPDISTRICT UNION 
select 'USERSTEMP' as Table_name,count(*) from LANDING_OMS.USERSTEMP UNION 
select 'WORKFLOWS' as Table_name,count(*) from LANDING_OMS.WORKFLOWS UNION 
select 'WORKFLOWSTEPS' as Table_name,count(*) from LANDING_OMS.WORKFLOWSTEPS UNION 
select 'CBMCAPACITY' as Table_name,count(*) from LANDING_OMS.CBMCAPACITY UNION 
select 'TOURSTATUSES' as Table_name,count(*) from LANDING_OMS.TOURSTATUSES UNION 
select 'AREADETAILSCONFIGURATION_2022' as Table_name,count(*) from LANDING_OMS.AREADETAILSCONFIGURATION_2022 UNION 
select 'ASPNETUSERROLES' as Table_name,count(*) from LANDING_OMS.ASPNETUSERROLES UNION 
select 'CONFIGUR' as Table_name,count(*) from LANDING_OMS.CONFIGUR UNION 
select 'CONFIGURATION' as Table_name,count(*) from LANDING_OMS.CONFIGURATION UNION 
select 'DATALOGS' as Table_name,count(*) from LANDING_OMS.DATALOGS UNION 
select 'DISTRIBUTIONCENTER21102019' as Table_name,count(*) from LANDING_OMS.DISTRIBUTIONCENTER21102019 UNION 
select 'EMAILNOTIFICATIONLOG' as Table_name,count(*) from LANDING_OMS.EMAILNOTIFICATIONLOG UNION 
select 'LOOKUPITEMCODE' as Table_name,count(*) from LANDING_OMS.LOOKUPITEMCODE UNION 
select 'LOOPINGSTORESCONFIGURATION' as Table_name,count(*) from LANDING_OMS.LOOPINGSTORESCONFIGURATION UNION 
select 'NORMAORDERS' as Table_name,count(*) from LANDING_OMS.NORMAORDERS UNION 
select 'NUMBERS' as Table_name,count(*) from LANDING_OMS.NUMBERS UNION 
select 'ORDERVERSIONENTRY' as Table_name,count(*) from LANDING_OMS.ORDERVERSIONENTRY UNION 
select 'REASONROLE' as Table_name,count(*) from LANDING_OMS.REASONROLE UNION 
select 'RMSWAREHOUSE' as Table_name,count(*) from LANDING_OMS.RMSWAREHOUSE UNION 
select 'RMSWAREHOUSEDICOUNTS_BK' as Table_name,count(*) from LANDING_OMS.RMSWAREHOUSEDICOUNTS_BK UNION 
select 'SALESCHANNELS' as Table_name,count(*) from LANDING_OMS.SALESCHANNELS UNION 
select 'CARS' as Table_name,count(*) from LANDING_OMS.CARS UNION 
select 'INTERMEDIATEONLINEORDERS' as Table_name,count(*) from LANDING_OMS.INTERMEDIATEONLINEORDERS UNION 
select 'NEW_SHENCHTB' as Table_name,count(*) from LANDING_OMS.NEW_SHENCHTB UNION 
select 'REG' as Table_name,count(*) from LANDING_OMS.REG UNION 
select 'STOREAREA' as Table_name,count(*) from LANDING_OMS.STOREAREA UNION 
select 'REASONS' as Table_name,count(*) from LANDING_OMS.REASONS UNION 
select 'SECONDARYDISTIBUTIONCENTER' as Table_name,count(*) from LANDING_OMS.SECONDARYDISTIBUTIONCENTER UNION 
select 'STORE_CONNECTION' as Table_name,count(*) from LANDING_OMS.STORE_CONNECTION UNION 
select 'WFACTIONS' as Table_name,count(*) from LANDING_OMS.WFACTIONS UNION 
select '__MIGRATIONHISTORY' as Table_name,count(*) from LANDING_OMS.__MIGRATIONHISTORY UNION 
select 'MISSING_DATA_NPS_TEMP' as Table_name,count(*) from LANDING_OMS.MISSING_DATA_NPS_TEMP UNION 
select 'STORESCONNECTION' as Table_name,count(*) from LANDING_OMS.STORESCONNECTION UNION 
select 'SYNCHONLINELOGS' as Table_name,count(*) from LANDING_OMS.SYNCHONLINELOGS UNION 
select 'SUBREGIONS' as Table_name,count(*) from LANDING_OMS.SUBREGIONS UNION 
select 'ACTIONREASONS' as Table_name,count(*) from LANDING_OMS.ACTIONREASONS UNION 
select 'AREALOOPINGSTORES' as Table_name,count(*) from LANDING_OMS.AREALOOPINGSTORES UNION 
select 'ASPNETUSERLOGINS' as Table_name,count(*) from LANDING_OMS.ASPNETUSERLOGINS UNION 
select 'ASPNETUSERS' as Table_name,count(*) from LANDING_OMS.ASPNETUSERS UNION 
select 'DISTRIBUTIONCENTER' as Table_name,count(*) from LANDING_OMS.DISTRIBUTIONCENTER UNION 
select 'DISTRICTS18102019' as Table_name,count(*) from LANDING_OMS.DISTRICTS18102019 UNION 
select 'DOWNPAYMENTSLA' as Table_name,count(*) from LANDING_OMS.DOWNPAYMENTSLA UNION 
select 'DRAFTONLINEORDER_21112019' as Table_name,count(*) from LANDING_OMS.DRAFTONLINEORDER_21112019 UNION 
select 'EXCEPTIONLOG' as Table_name,count(*) from LANDING_OMS.EXCEPTIONLOG UNION 
select 'INSTALLMENTORDERS' as Table_name,count(*) from LANDING_OMS.INSTALLMENTORDERS UNION 
select 'OLD_DISTRICT' as Table_name,count(*) from LANDING_OMS.OLD_DISTRICT UNION 
select 'ORDERSSYNCLOG' as Table_name,count(*) from LANDING_OMS.ORDERSSYNCLOG UNION 
select 'SHEET' as Table_name,count(*) from LANDING_OMS.SHEET UNION 
select 'STOCKTMP' as Table_name,count(*) from LANDING_OMS.STOCKTMP UNION 
select 'SUBREGIONSTORES' as Table_name,count(*) from LANDING_OMS.SUBREGIONSTORES UNION 
select 'EMAILNOTIFICATION' as Table_name,count(*) from LANDING_OMS.EMAILNOTIFICATION UNION 
select 'LOYALTYSERVICEHEADER' as Table_name,count(*) from LANDING_OMS.LOYALTYSERVICEHEADER UNION 
select 'REGIONS21102019' as Table_name,count(*) from LANDING_OMS.REGIONS21102019 UNION 
select 'STOREDLOGACTION' as Table_name,count(*) from LANDING_OMS.STOREDLOGACTION UNION 
select 'STOREMOBILITYUSERROLES' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERROLES UNION 
select 'STOREMOBILITYUSERSBRAND' as Table_name,count(*) from LANDING_OMS.STOREMOBILITYUSERSBRAND UNION 
select 'TAXEXEMPTION' as Table_name,count(*) from LANDING_OMS.TAXEXEMPTION UNION 
select 'QUOTATIONENTRY' as Table_name,count(*) from LANDING_OMS.QUOTATIONENTRY UNION 
select 'TOURS' as Table_name,count(*) from LANDING_OMS.TOURS UNION 
select 'VERSIONCONFIGURATION' as Table_name,count(*) from LANDING_OMS.VERSIONCONFIGURATION UNION 
select 'WFSTEPS' as Table_name,count(*) from LANDING_OMS.WFSTEPS UNION 
select 'LOG' as Table_name,count(*) from LANDING_OMS.LOG UNION 
select 'OMSAREA' as Table_name,count(*) from LANDING_OMS.OMSAREA UNION 
select 'ORDERENTRY' as Table_name,count(*) from LANDING_OMS.ORDERENTRY UNION 
select 'REGIONS' as Table_name,count(*) from LANDING_OMS.REGIONS UNION 
select 'ORDERVESIONS' as Table_name,count(*) from LANDING_OMS.ORDERVESIONS; 


